language: node_js
node_js:
  - '4.2'
before_install:
    - npm install -g gulp
    - npm install -g bower
    - cd front-end
install:
    - npm install
    - bower install
    - gulp --cordova "prepare"
script:
    - gulp build
test:
    - cd ../back-end
    - npm install
    - npm run start-dev &
    - sleep 5
    - npm test
