language: node_js
node_js:
  - '4.2'
before_install:
    - cd front-end
install:
    - npm install
    - npm run build-dev &
    # - gulp --cordova "prepare"
script:
    - cd ../back-end
    - npm install
    - npm run start-dev &
    - sleep 5
    - npm test
